### ISSUE TITLE
cfme.infrastructure.virtual_machines.get_first_vm does not exist

### ISSUE THREAD

**Issue by psav** [ManageIQ/integration_tests#1068]
E                   vm_name = virtual_machines.get_first_vm()
E               AttributeError: 'module' object has no attribute 'get_first_vm'

cfme.infrastructure.virtual_machines does not contain a function called get_first_vm()

However, I think we should also be careful and potentially create a vm for this case. Just removing the first vm from the appliance is potentially dangerous.

**Comment by jkrocil** [comment]
This is actually still valid: https://github.com/RedHatQE/cfme_tests/blob/ba1ac6b442b290d6222d92bd9229a775226b57cd/cfme/tests/configure/test_access_control.py#L378 (woah)

**Comment by mshriver** [comment]
I don't believe this issue is valid any longer, there's no call to this function.

Design wise, we are currently consolidating many of the fixtures that are creating or picking existing VM's.
