### ISSUE TITLE
Current user check / logout fails when addition  top_right menu is added in the appliance

### ISSUE THREAD

**Issue by rananda** [ManageIQ/integration_tests#2513]
When top_right menu is added in the appliance (external menu plugin support - https://github.com/ManageIQ/manageiq/pull/1680), logged in user check (current user) and logout fails as the existing code is not able to locate the correct object in the UI.  Need to modify the existing code to accomodate the menu plugin feature.

**Comment by jkrocil** [comment]
@rananda is this still a valid issue?

**Comment by psav** [comment]
This is fixed
