### ISSUE TITLE
5.6 BZ blockers are not uncollected in upstream

### ISSUE THREAD

**Issue by jkrocil** [ManageIQ/integration_tests#2974]
This is the issue:
https://github.com/RedHatQE/cfme_tests/blob/master/utils/bz.py#L316

@mfalesni ^

Current `product.latest_version` in bugzilla is already 5.7.0 unfortunately.

**Comment by mshriver** [comment]
We're no longer testing 5.6, and are not experiencing any issues with blocker BZs and collection against specific CFME versions.
