### ISSUE TITLE
form validation needs to be updated

### ISSUE THREAD

**Issue by dajohnso** [ManageIQ/integration_tests#3036]
With the release of MIQ Darga (CF4.1) , form validation feedback has changed and needs to be update.  Prior releases threw a flash message at the top of the page after form submit, now it is next to the field and done before form submission

![new_validation](https://cloud.githubusercontent.com/assets/477564/15635900/57846014-25bb-11e6-8c5c-77eead2d541b.png)

**Comment by mfalesni** [comment]
I guess this might be more generalized so we can specify required fields in the form and then parametrize a form validation testcase by combinations of unfilled fields and it would check if it displays the *required* text.

**Comment by mshriver** [comment]
Specific test cases for provider form validation cover this type of help-text validation instead of through flash messages.

I would view @mfalesni comment as a very valid enhancement, separate from the specific request that the issue was written for.
