### ISSUE TITLE
Fix extend_nav to work with new class instance menu nav object

### ISSUE THREAD

**Issue by psav** [ManageIQ/integration_tests#3060]

**Comment by lukas-bednar** [comment]
Is this related to change of locator for
```
<li class='list-group-item'>
```
vs
```
<li class='list-group-item secondary-nav-item-pf'>
```
?
we are failing containers tests because of this.
Or is this issue about something different ?

**Comment by mfalesni** [comment]
@lukas-bednar No, it is just htat extend_nav assumes static tree struture I guess, right @psav ?

**Comment by psav** [comment]
As force_navigate, ui_navigate and menu are being deprecated, this can close
