### ISSUE TITLE
Fix Landing pages tests

### ISSUE THREAD

**Issue by psav** [ManageIQ/integration_tests#3083]
Landing pages currently pull in landing pages from the cfme_data and are singular (ie, not dependant on version) with the new menu system, these need to be updated. We either 
1. move them into the menu code base
2. there is a `sections` part of the Menu object in `cfme.web_ui.menu` that we could read from,
3. or we have multiple version dependent sets in the cfme_data

I like 2 the best, but it may not be possible.

**Comment by mshriver** [comment]
The landing pages are now defined locally in the test module, and include lists for the active versions of MIQ/CFME.

The tests are version picking the landing pages and passing in actively tested versions.
