### ISSUE TITLE
Add document on "common" py.test switches (--use-provider) etc

### ISSUE THREAD

**Issue by psav** [ManageIQ/integration_tests#3115]

**Comment by dajoRH** [comment]
Right, -m provider_related   or     -m uses_testgen

**Comment by mshriver** [comment]
I hesitate to document these outside of the actual plugin documentation (help text). As anything will quickly becomes outdated as the plugins are enhanced/added/removed and the documentation falls behind.

They _should_ be self documenting, and in unique pytest option groups that help to organize them in `py.test --help` output.

One issue that existed when this was written, was that many of the fixtures and markers were not properly registered with pytest, and were not included in the output of py.test --help, effectively hiding them unless you went and read all the modules directly.  That was resolved with the move to py3+pytest5, and all of our plugins/fixtures/markers are now properly documented/registered.
