### ISSUE TITLE
-m provider_related no longer works

### ISSUE THREAD

**Issue by dajoRH** [ManageIQ/integration_tests#3171]
We added the internally generated mark provider_related to be used in conjunction with --use-provider <provider> so we could only run tests that are specific to the provider.  Without it, the test collected would be anything non-parameterized through testgen, like general ui tests, along with the provider paramaterized tests specific to the provider that pass through testgen.  

Example (only run tests specific to rhevm36 provider integration):
py.test cfme/tests/infrastructure --use-provider rhevm36 -m provider_related

This appears to have broken at some point and need to be fixed.

A partial workaround is to pass "-m uses_testgen" instead.  It still pulls in some extra tests but limits it to test suites that use testgen.  For example, test_providers.py would run the specific crud tests but also run the provider validation tests which isn't ideal but far less than running without (when you only want to run the specific provider integration tests).  This all needs documentation in #3115

**Comment by RonnyPfannschmidt** [comment]
a short term workaround would be to put a mark into the provider related test items,

i propose replacing `--use-provider foo -m provider_related` with a `--only-for-provider` option that does select only testgen based tests that use the specific provider
