### ISSUE TITLE
RHEV C&U creds don't get added when a RHEV provider is added

### ISSUE THREAD

**Issue by nachandr** [ManageIQ/integration_tests#3404]
While writing automation for C&U, I noticed that no attempt is made to add the C&U credentials in the CFME UI when a RHEV provider is added.

This used to work earlier, in that, when a RHEV provider was added, the C&U creds would also be added and validated.

**Comment by dajohnso** [comment]
@mfalesni this sounds related to the recent tabfields work, can you take a peek?

**Comment by mfalesni** [comment]
This works for me:
```python
from utils.providers import get_crud
p = get_crud('rhevm36')
p.create()
```

I can see it creating the provider and inserting and validating the data in the create form. I pulled the latest master of tests.

Maybe you used a provider that does not have `candu_credentials` in its yaml entry? Old yamls? Old master?

If it works for you, please close this issue :)

**Comment by nachandr** [comment]
Closing this issue.
