### ISSUE TITLE
Unable to remove providers through the UI

### ISSUE THREAD

**Issue by nachandr** [ManageIQ/integration_tests#3405]
Here's a link to my WIP PR:
https://github.com/ManageIQ/integration_tests/pull/3161

While testing this, I noticed that providers wouldn't get removed.Here's the stacktrace.
http://paste.fedoraproject.org/427992/

**Comment by dajohnso** [comment]
@jkrocil sounds like a good one for one of your guys perhaps.

**Comment by mfalesni** [comment]
That just needs casting from int to str (I think) ...

**Comment by jkrocil** [comment]
@mshriver was asking about this one as well
