### ISSUE TITLE
Metrics test made to always pass

### ISSUE THREAD

**Issue by jaryn** [ManageIQ/integration_tests#3934]
See the https://github.com/ManageIQ/integration_tests/pull/3906#pullrequestreview-15303144

**Comment by jaryn** [comment]
Also, it assumes the metrics is running on the provider hostname (` hostname = conf.cfme_data.get('management_systems', {})[provider.key]\`), which may not be (and I think often isn't)  true, depending on the configuration of OpenShift DNS routing.

**Comment by mshriver** [comment]
This test has since been refactored from when this issue was written.
