### ISSUE TITLE
test_tenant failed, delete :UnboundLocalError: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by rrasouli** [ManageIQ/integration_tests#3953]
In my setup RHOS10 and CFME 5.7 latest, the cloud tenant crud failed on delete method, the provider tenant has already deleted, in test the failure is immediate.

@mshriver @psav 
py.test test_tenant.py --use-provider oc_ci
no test annotation found in None
============================================= test session starts ==============================================
platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.4.32, pluggy-0.3.1 -- /root/cfme_tests/bin/python
cachedir: ../../../.cache
rootdir: /root/cfme_tests/cfme_tests, inifile: pytest.ini
plugins: wait-for-1.0.8
collected 1 items 

Appliance's streams: [downstream, 5.7]

test_tenant.py::test_tenant_crud[oc_ci] FAILED

=================================================== FAILURES ===================================================
___________________________________________ test_tenant_crud[oc_ci] ____________________________________________

tenant = <cfme.cloud.tenant.Tenant object at 0x7f02fc049b90>

    @pytest.mark.uncollectif(lambda: current_version() < '5.7')
    def test_tenant_crud(tenant):
        """ Tests tenant create and delete
    
        Metadata:
            test_flag: tenant
        """
        tenant.create(cancel=True)
        assert not tenant.exists()
    
        tenant.create()
        assert tenant.exists()
    
>       tenant.delete(from_details=False, cancel=True)

test_tenant.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cfme.cloud.tenant.Tenant object at 0x7f02fc049b90>, cancel = True, from_details = False, wait = True

    def delete(self, cancel=False, from_details=True, wait=True):
        if current_version() < '5.7':
            raise OptionNotAvailable('Cannot delete cloud tenants in CFME < 5.7')
        if from_details:
            # Generates no alert or confirmation
            try:
                navigate_to(self, 'Details')
            except Exception as ex:
                # Catch general navigation exceptions and raise
                raise TenantNotFound('Exception while navigating to Tenant details: {}'
                                     .format(ex))
            cfg_btn('Delete Cloud Tenant')
        else:
            # Have to select the row in the list
            navigate_to(self, 'All')
            # double check we're in List View
            tb.select('List View')
            found = False
            for page in paginator.pages():
                try:
                    listview_checktable.select_row_by_cells(
                        {'Name': self.name,
                         'Cloud Provider': self.provider.name})
                    found = True
                except NoSuchElementException:
                    continue
                else:
                    break
            if not found:
                raise TenantNotFound('Could not locate tenant for delete by selection')
            cfg_btn('Delete Cloud Tenants', invokes_alert=True)
            sel.handle_alert(cancel=cancel)
    
        # In both cases the flash message is the same
        if not cancel:
            result = flash.assert_success_message('Delete initiated for 1 Cloud Tenant.')
            if wait:
                result = self.wait_for_disappear()
    
>       return result
E       UnboundLocalError: local variable 'result' referenced before assignment

../../cloud/tenant.py:109: UnboundLocalError
========================================== 1 failed in 444.08 seconds ==========================================
collecting artifacts

**Comment by rrasouli** [comment]
seems like manageIQ issue in RHOS10

**Comment by rrasouli** [comment]
A solution would be, refresh provider is over then re examine tenants list

**Comment by rrasouli** [comment]
cfme/tests/cloud/test_tenant.py::test_tenant_crud[oc_ci] FAILED

=================================== FAILURES ===================================
___________________________ test_tenant_crud[oc_ci] ____________________________

tenant = <cfme.cloud.tenant.Tenant object at 0x5487550>

    @pytest.mark.uncollectif(lambda: current_version() < '5.7')
    def test_tenant_crud(tenant):
        """ Tests tenant create and delete
    
        Metadata:
            test_flag: tenant
        """
    
        tenant.create(cancel=True)
        assert not tenant.exists()
    
        tenant.create()
        assert tenant.exists()
    
        tenant.update({'name': 'my_new_name'})
        # BZ#1411112 Delete/update cloud tenant
        #  not reflected in UI in cloud tenant list
        # tenant.provider.refresh_provider_relationships()
        # tenant.wait_for()
        assert tenant.exists()
    
>       tenant.delete(from_details=False, cancel=True)

cfme/tests/cloud/test_tenant.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cfme.cloud.tenant.Tenant object at 0x5487550>, cancel = True
from_details = False, wait = True

    def delete(self, cancel=False, from_details=True, wait=True):
        if current_version() < '5.7':
            raise OptionNotAvailable('Cannot delete cloud tenants in CFME < 5.7')
        if from_details:
            if cancel:
                raise OptionNotAvailable('Cannot cancel cloud tenant delete from details page')
            # Generates no alert or confirmation
            try:
                navigate_to(self, 'Details')
            except Exception as ex:
                # Catch general navigation exceptions and raise
                raise TenantNotFound('Exception while navigating to Tenant details: {}'
                                     .format(ex))
            cfg_btn('Delete Cloud Tenant')
        else:
            # Have to select the row in the list
            navigate_to(self, 'All')
            # double check we're in List View
            tb.select('List View')
            found = False
            for page in paginator.pages():
                try:
                    listview_checktable.select_row_by_cells(
                        {'Name': self.name,
                         'Cloud Provider': self.provider.name})
                    found = True
                except NoSuchElementException:
                    continue
                else:
                    break
            if not found:
>               raise TenantNotFound('Could not locate tenant for delete by selection')
E               TenantNotFound: Could not locate tenant for delete by selection

cfme/cloud/tenant.py:114: TenantNotFound
========================== 1 failed in 237.43 seconds ==========================
collecting artifacts

@mshriver the new updated tenant does not assigned to self

**Comment by mshriver** [comment]
The Tenant entity class methods have since been modified, and no longer hit an UnboundLocal exception.
