### ISSUE TITLE
Replace open_edit with navmazing

### ISSUE THREAD

**Issue by psav** [ManageIQ/integration_tests#4322]
For the Instances/Vms/Images, there is a core method on the common VM object that opens the edit page. This should be a navmazing step if not already and we should replace all the open_edit methods

**Comment by mshriver** [comment]
This should wait until infra.virtual_machines is updated to widgetastic: 
https://github.com/ManageIQ/integration_tests/pull/5113

With #4872 and #5113, converting/replacing this method will be much cleaner and more consistent for both infra and cloud vms/instances.

**Comment by mshriver** [comment]
The common VM method, open_edit, uses `navigate_to`
