### ISSUE TITLE
Fix Widgetastic_patternfly.Button for toolbar view buttons in 56z

### ISSUE THREAD

**Issue by mshriver** [ManageIQ/integration_tests#4351]
The `__locator__` for widgetastic_patternfly.Button includes types and classes in the XPATH that don't match the toolbar view button elements in 56z.  They do match 57z.

Update the locator or otherwise provide a class to represent these view buttons as widgets.

**Comment by mfalesni** [comment]
The thing is whether it is a patternfly button or not. I will check it.

**Comment by mshriver** [comment]
I'm trying to work through this as well, looking at the locator it should be catching the button.

**Comment by mshriver** [comment]
It's because of `contains(@class, "btn")` in the widgetastic_patternfly.Button locator

**Comment by mshriver** [comment]
Fixed with #4383
