### ISSUE TITLE
In chargeback rate assignment - 'Add' button

### ISSUE THREAD

**Issue by gshefer** [ManageIQ/integration_tests#4409]
In chargeback rate assignment form, when the form is filled and we are about to press the 'Add' (assignment) button, the Add button of the row is pressed instead:
Reproduction branch: https://github.com/gshefer/integration_tests/tree/chargeback_reports
Reproduction file: cfme/tests/containers/test_chargeback.py

![cfme chargeback](https://cloud.githubusercontent.com/assets/21076742/24146804/fc7f99f4-0e3f-11e7-9ca6-a505b1532157.png)

**Comment by mfalesni** [comment]
Yes, I will add additional matching conditions for the buttons, probably the classes on it. Not sure how we will do it with the gray add buttons, they will have to live in a sub-view fenced by a locator.

**Comment by mfalesni** [comment]
So the referenced PR will enable you to fence the query only to the blue buttons by class. Should we add support for the gray Add buttons, their lookup will have to be fenced by a nested view.
