### ISSUE TITLE
When add compute chargeback rate - add button is grayed-out

### ISSUE THREAD

**Issue by gshefer** [ManageIQ/integration_tests#4465]
When creating compute chargeback, the form is filled with valid values and the add button is keeping to be unclickable, that causes the [fixture](https://github.com/gshefer/integration_tests/blob/chargeback_reports/cfme/tests/containers/test_chargeback.py#L33) to [fail to add the rate](https://github.com/gshefer/integration_tests/blob/chargeback_reports/cfme/tests/containers/test_chargeback.py#L55).
Note: after some analysis, looks like the description testbox fill is bad for some reason (i.e. it is not really detected as "filled").
Reproduction script: https://github.com/gshefer/integration_tests/blob/chargeback_reports/cfme/tests/containers/test_chargeback.py
![image](https://cloud.githubusercontent.com/assets/21076742/24454409/70e88e36-1494-11e7-8469-1b0556ca4e7f.png)

**Comment by mfalesni** [comment]
Can you also reproduce it manually? Or it is happening only in the automation?

**Comment by gshefer** [comment]
Only in the automation.

**Comment by mfalesni** [comment]
Could not reproduce:
```
Appliance's streams: [5.8, downstream]

cfme/tests/containers/test_chargeback.py::test_new_chargeback_rate[cm-env2] PASSED
cfme/tests/containers/test_chargeback.py::test_assign_compute_custom_rate[cm-env2] PASSED
cfme/tests/containers/test_chargeback.py::test_chargeback_fixed_rate[cm-env2] ERROR
```

The error is caused by a table not existing, not by error you reported.
