### ISSUE TITLE
quickstart shows pyc files

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/integration_tests#4936]
Quickstart currently doesn't add below lines to the venv/bin/activate file 
export PYTHONPATH='{cfme_workspace}/integration_tests'
export PYTHONDONTWRITEBYTECODE=yes
export CFME_TESTS_KEY="'cat {cfme_workspace}/integration_tests/.yaml_key'"

**Comment by RonnyPfannschmidt** [comment]
all that is unneeded

* pythonpath is not needed due to develop install
* dontwritebytecode is set in a pth file
* the test key is loaded from a file and we warn about the missing file

**Comment by vatsalparekh** [comment]
But it still see the pyc files being created in all the directories

**Comment by RonnyPfannschmidt** [comment]
that points to a bug which needs debugging
