### ISSUE TITLE
Can't add any Openstack provider with Ceilometer event source

### ISSUE THREAD

**Issue by okolisny** [ManageIQ/integration_tests#5028]
Can't setup Openstack (both Infra and Cloud) provider using framework with `event_stream: Ceilometer`, because it tries to click on Validate button which doesn't exist for Ceilometer event source.

**Comment by izapolsk** [comment]
#5031 should fix this issue. Please test it since we don't have any provider with Oscilometer in our configs

**Comment by okolisny** [comment]
@izapolsk it works, thanks
