### ISSUE TITLE
[Sprout] Sever Error (500) Observed when Navigating to Bug Tab

### ISSUE THREAD

**Issue by jawatts** [ManageIQ/integration_tests#5239]
The CFME QE Sprout instance, a Server Error(500) has been observed as the result of :
1) Navigating to the "Bug" tab as seen by one user
2) 'Bugs Reported by me" sub tab as seen by another user

**Comment by mshriver** [comment]
I took an initial look at it and could click other sub tabs but 'Bugs Reported by me' produced the 500. We'll create card to record local sprout server log errors.  May be a server misconfiguration and not necessarily sprout bug.

**Comment by mfalesni** [comment]
This is wontfix, I will actually remove that Bugs section altogether in foreseeable future.
