### ISSUE TITLE
Navigation to Add Provider menu stopped working on v5.9 

### ISSUE THREAD

**Issue by pavelzag** [ManageIQ/integration_tests#5599]
This part seems to bring me to the Containers Providers main menu and not to the Add Provider screen as it should and as it still works on older versions:

add_view = navigate_to(self, 'Add')
in 
common/provider.py

**Comment by gshefer** [comment]
This failure expected.
The reason for this is that the setup provider UI has been (dramatically) changed.
We should update the widgetastic objects accordingly.

**Comment by mshriver** [comment]
I believe this is being fixed in #5604 by @jawatts
