### ISSUE TITLE
HostQuadIconEntity.data throws KeyError on 5.9

### ISSUE THREAD

**Issue by okolisny** [ManageIQ/integration_tests#5603]
HostQuadIconEntity.data doesn't get such info as 'state' or 'no_vm' and throws KeyError in 5.9
The same code base works as expected with CFME 5.8.

Tracebacks and examples (follow KeyError failures):
 https://rhos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Director/view/CFME_RHOS_Integration/job/rhos11_cfme59_integration/2/TEST_REPORT/

**Comment by psav** [comment]
This should be fixed very shortly

**Comment by izapolsk** [comment]
Yes the fix is ready. I hope it will be merged today.

**Comment by izapolsk** [comment]
fix https://github.com/ManageIQ/integration_tests/pull/5798
