### ISSUE TITLE
miq shell not reloading the appliance IP

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/integration_tests#5662]
After using `miq sprout` command with `--populate-yamls` & using it in `miq shell`, if I go to sprout website and create a appliance manually, and paste its IP in the env.yaml, even after restarting `miq shell` it still takes the IP of the appliance that was last called through the `miq sprout`

**Comment by psav** [comment]
I just checked this and it is working as expected. Are you modifying ```env.yaml```, or ```env.local.yaml```. The local one overrides the other. ```--populate-yaml``` option populates the loca file, so if you were then editing ```env.yaml``` you would not see that IP when using ```miq shell```

**Comment by vatsalparekh** [comment]
Yes i was editing the `env.yaml`, @izapolsk had suggested that this was a issue with ipython env or something related to it, so had opened the issue.

**Comment by izapolsk** [comment]
@vatsalparekh, I recommended you to restart ipython and you stated that ipython had used old ip after restart. So, it looked like a bug. I didnt know that both yaml files are present in your env.
