### ISSUE TITLE
[5.9] Failure to add a Containers Provider with SSL due to a change in Add Providers screen

### ISSUE THREAD

**Issue by pavelzag** [ManageIQ/integration_tests#6120]
/tests/containers/test_ssl_providers.py fails due to a change in Add Providers screen.
The code for element in 5.8 is:

`<div id="flash_msg_div" style=""><div class="flash_text_div" title="Click to remove message"><div class="alert alert-success"><span class="pficon pficon-ok"></span><strong>Credential validation was successful</strong></div></div></div>`

In 5.9 it's:

`<div id="flash_msg_div" style=""><div class="flash_text_div"><div class="alert alert-success"><button class="close" data-dismiss="alert"><span class="pficon pficon-close"></span></button><span class="pficon pficon-ok"></span><strong>Credential validation was successful</strong></div></div></div>
`

Error message:

```
self = FlashMessages('.//div[@id="flash_msg_div"]/div[@id="flash_text_div" or contains(@class, "flash_text_div")]')

    def assert_no_error(self):
        self.logger.info('asserting there are no error messages')
        for message in self.messages:
            if message.type not in {'success', 'info'}:
                self.logger.error('%s: %r', message.type, message.text)
>               raise AssertionError('assert_no_error: {}: {}'.format(message.type, message.text))
E               AssertionError: assert_no_error: error: Credential validation was not successful: Failed to open TCP connection to xxxx.redhat.com:443 (Connection refused - connect(2) for "xxxx.redhat.com" port 443)
```

**Comment by mshriver** [comment]
This test is being updated and modified for SSL certificate changes.  This change for the flash message is actually handled in the BaseLoggedInPage view implementation
