### ISSUE TITLE
VolumeBackupCollection.all() produces AttributeError without filter

### ISSUE THREAD

**Issue by mshriver** [ManageIQ/integration_tests#6123]
This line generates an AttributeError if there is no provider filter applied:
https://github.com/ManageIQ/integration_tests/blob/master/cfme/storage/volume_backup.py#L195

The method needs to be updated to operate without exception when there is no provider filter present, returning all volume backups visible by the appliance on all providers.

**Comment by digitronik** [comment]
@mshriver adding exception. @psav also suggested me about this method failure.

**Comment by mshriver** [comment]
Fixed by #6148
