### ISSUE TITLE
Updates Required For cfme.tests.containers.test_ssl_providers

### ISSUE THREAD

**Issue by jawatts** [ManageIQ/integration_tests#6409]
cfme.tests.containers.test_ssl_providers are failing due to not having the correct certificate on the CFME appliance. A solution to put the OCP certificate on the CFME appliance is needed. 

@shalomnaim1 is taking the lead to implemented this solution.

**Comment by shalomnaim1** [comment]
I wrote a fixture for sync the certifications, you welcome to take a look at it --> https://github.com/ManageIQ/integration_tests/pull/6432

**Comment by shalomnaim1** [comment]
@jawatts I don't think this necessary because I am removing this line in my PR, I think that enough for PRT to run
