### ISSUE TITLE
ImportError: No module named cfme.utils.conf

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/integration_tests#7123]
https://github.com/ManageIQ/integration_tests/blob/60411952c9a8e80b6d142f554b73b101d21024f9/cfme/utils/dockerbot/dockerbot.py#L2

➜  dockerbot git:(master) ✗ python dockerbot.py 
Traceback (most recent call last):
  File "dockerbot.py", line 2, in <module>
    from cfme.utils.conf import docker as docker_conf
ImportError: No module named cfme.utils.conf
➜  dockerbot git:(master) ✗ 

Hey @RonnyPfannschmidt  I was trying to run docker bot but it is complaining about this file. What do we need to do? I am willing to try to fix this issue locally and then submit PR as well.

**Comment by RonnyPfannschmidt** [comment]
@kedark3 atf irst glance you aren't in a virtualenv, please follow the quick-start documentation and enable that virtualenv - afterwards it should work and in case it doesn't please catch me in a chat

**Comment by kedark3** [comment]
@RonnyPfannschmidt that indeed solved this issue. closing. Thanks.
