### ISSUE TITLE
Links on the Readme.md file are wrong

### ISSUE THREAD

**Issue by caiocmpaes** [ManageIQ/integration_tests#7126]
Getting Started link on the Readme:
https://cfme-tests.readthedocs.io/getting_started.html

Correct Link:
https://cfme-tests.readthedocs.io/en/master/getting_started.html

It's the first time I'm going to run the Integration Tests, so I don't know if the links are outdated here or the documentation page is showing the wrong path `/en/master/**`

**Comment by RonnyPfannschmidt** [comment]
thanks for the note, i might have accidentally introduced this while fixing a doc building issue

**Comment by RonnyPfannschmidt** [comment]
i added a prefix based redirect from `/` to `/en/master/**`
