### ISSUE TITLE
[Automation Blocker] JavaScript code in page_has_changes breaks SSUI tests

### ISSUE THREAD

**Issue by jan-zmeskal** [ManageIQ/integration_tests#7297]
Recent [change](https://github.com/ManageIQ/integration_tests/commit/d62f94390262191a83b82050e9c58795ff795b31) in integration_tests causes problems with SSUI test cases. The variable `ManageIQ` that is in use there apparently is not defined when the code is executed. The resulting error message during execution can be seen for example [here](https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/47/testReport/cfme.tests.ssui/test_ssui_myservice/test_myservice_crud_rhv_cfme_integration_ViaSSUI_/).

As far as I know, this affects pretty much all the SSUI tests (with maybe some exceptions).

**Comment by psav** [comment]
Do you have a suggestion for fixing this? Can you point to any code that you know is running this?

**Comment by izapolsk** [comment]
I'm looking into this.

**Comment by izapolsk** [comment]
fix https://github.com/ManageIQ/integration_tests/pull/7330

**Comment by jan-zmeskal** [comment]
@izapolsk Can we close? #7330 is merged.

**Comment by izapolsk** [comment]
@jan-zmeskal, sure thing
