### ISSUE TITLE
[Bug] query_resource_attributes failes when querying tags of provision_requests

### ISSUE THREAD

**Issue by jan-zmeskal** [ManageIQ/integration_tests#7372]
If you run test case `cfme/tests/infrastructure/test_provisioning_rest.py::test_provision_attributes`, it fails with the following error: 

> E SoftAssertionError:
> E attribute "tags": status: 500, error: `LocalJumpError: no block given (yield)` (cfme/utils/rest.py:250)

Originally, I thought it's a product bug so I opened a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1592326). However, it turns out that [query_resource_attributes](https://github.com/ManageIQ/integration_tests/blob/e78daee7b1bebb1b53808022575bc426842ce059/cfme/utils/rest.py#L214) queries tags in following way:

`https://<appliance_ip>/api/provision_requests/<request_id>?attributes=tags`

According to [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1592326#c4) to the BZ such way of querying tags is not supported. Instead, we should do it like [this](https://manageiq.org/docs/reference/latest/api/reference/categories_tags#querying-tags). [query_resource_attributes](https://github.com/ManageIQ/integration_tests/blob/e78daee7b1bebb1b53808022575bc426842ce059/cfme/utils/rest.py#L214) or the test case must accommodate to that fact.

**Comment by mkoura** [comment]
It is a product bug as far as I'm concerned. I added comment to the BZ and changed it's status.
https://bugzilla.redhat.com/show_bug.cgi?id=1592326#c5

**Comment by jan-zmeskal** [comment]
@mkoura That's true, I've seen your comment - thank you for this! Then I suppose we might be able to close this issue. If tags should not be queried this way, then I suppose devs should remove tags from the return value of OPTIONS HTTP call and this method will work again, right? 
Also, I have one question. When we find a bug like this, should not we wrap the test case with BZ? I mean I can of course do that for the most current bug, but I see that are five or six bugs in more or less active state and the test case has not been wrapped for neither of them.

**Comment by mkoura** [comment]
@jan-zmeskal That's correct, once they remove it from "resources" section it will work as expected again. Also they should move it to "subcollections" section. Tags are subcollection and are not listed there ATM.

It is also true that we should add the BZ blocker, but ``query_resource_attributes`` is not the place the blocker belongs to. It is a general helper function for testing attributes and subcollections queries, designed to find exactly this type of bugs. The BZ blocker should go to the corresponding test itself, see e.g. [test_query_vm_attributes](https://github.com/ManageIQ/integration_tests/blob/master/cfme/tests/infrastructure/test_vm_rest.py#L39-L48)

**Comment by jan-zmeskal** [comment]
@mkoura Okay, I think the situation has been pretty much cleard in comments to the referenced BZ. Therefore closing this issue. Thank you for your help with this!
