### ISSUE TITLE
[Bug] test_child_tenant_quota_enforce_via_lifecycle_infra might be causing problem with subsequent provision requests

### ISSUE THREAD

**Issue by jan-zmeskal** [ManageIQ/integration_tests#7385]
This issue is quite complicated. I've already shared it with @anurag03. He investigated for a while but could not come up with a quick solution, so we decided together to track here for better transparency. I explained everything quite thoroughly to Anurag in my original email, therefore I'll just copy it here.

----------------------------------------------------------------------------------------------------------------------
Hello Anurag, I have a problem and I hope you could help me with solving it. I am reaching out to you since (according to git blame) you're an author of module cfme/tests/infrastructure/test_child_tenant.py. The following is a bit of a text wall, so brace youself.

Okay, so what went wrong? I probably began with adding test_child_tenant_quota_enforce_via_lifecycle_infra to integration_tests. Since you also added @rhv2 decorator, this test became part of regression suite that we use for RHV-CFME integration testing.
![image](https://user-images.githubusercontent.com/22600243/41659292-2c108ece-7499-11e8-9244-39fdab7aa542.png)
After that, I started noticing that some of our provisioning test cases fail with the following error:

TimedOutError: Could not do Request finished at /var/lib/jenkins/workspace/cfme-5.9-rhv-4.2-integration-test-dev/integration_tests/cfme/services/requests.py:54 in time

I noticed that those test cases were executed after some quota test cases, so I decided to execute Jenkins run with only three modules:
cfme/tests/infrastructure/test_child_tenant.py <- this one I suspected for potential cause of the problem
cfme/tests/infrastructure/test_project_quota.py <- and this one as well
cfme/tests/infrastructure/test_provisioning_dialog.py <- this is the module where provisioning requests timed out

You can check out the whole run [here](https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cfme-5.9-rhv-4.2-integration-test-dev/60/) yourself. Long story short, this is the outcome:
![image](https://user-images.githubusercontent.com/22600243/41659345-520fcb4e-7499-11e8-8c56-ebf9f2ae11c8.png)

All those test cases without PASSED are those that FAILED. That means that all test cases from cfme/tests/infrastructure/test_child_tenant.py were successful. All the other test cases failed because provisioning requests got stuck at "Pending Approval" stage. This is what CFME appliance looked like after it:
![image](https://user-images.githubusercontent.com/22600243/41659360-5969507c-7499-11e8-8c37-62d279360f43.png)

I believe that introduction of cfme/tests/infrastructure/test_child_tenant.py has something to do with it. My first idea was that maybe that the user that was created during your test is still logged-in and tries to provision new VMs with his limited quotas. However, as you can see, all of the requests are made by Administrator, so that is not the case. To be completely honest, I have no idea what went wrong during that test. The only thing I know (or at least the evidence seems to suggest) that before executing cfme/tests/infrastructure/test_child_tenant.py, Administrator can make provision requests that get auto-approved. After that, it's no longer true.

Could you please help me and look into that? Any help would be highly appreciated. Thank you!

-----------------------------------------------------------------------------------------------------------------------------

It's very well possible that my assumptions are wrong. However, I could not find any better explanation for this so far.

**Comment by anurag03** [comment]
I want to add my observation which is that, this issue is not reproducible for 5.8 appliance but can be only found on 5.9 appliance. https://github.com/ManageIQ/integration_tests/pull/7255 is the PR which tries to test the same thing for cloud provider.

**Comment by jan-zmeskal** [comment]
This might actually be a product bug, let's see what the resolution is: https://bugzilla.redhat.com/show_bug.cgi?id=1636958

**Comment by mshriver** [comment]
According to the BZ and comments from MIQ devs, the test should not be using the super_admin role for its group.
