### ISSUE TITLE
Pycurl import error on Fedora 28

### ISSUE THREAD

**Issue by valaparthvi** [ManageIQ/integration_tests#7399]
I'm facing pycurl `ImportError` while running tests and miq shell in my local virtual environment.

Package: pycurl==7.43.0.1
Operating System: Fedora 28
Error: 
``` 
File "/home/pvala/code/cfme_workspace/cfme_venv/lib/python2.7/site-packages/curl/__init__.py", line 7, in <module>
    import sys, pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (nss)
```

Note: Changing the pycurl version to 7.43.0.2 resolves this issue. I'd like to work on it, once the issue is confirmed.

**Comment by valaparthvi** [comment]
Looks like @RonnyPfannschmidt already added a solution [here](https://github.com/ManageIQ/integration_tests/pull/6401/files).

**Comment by RonnyPfannschmidt** [comment]
the credit should go to @jan-zmeskal who documented the requirements as abi between fedora 27 and 28 changes ^^

**Comment by mshriver** [comment]
Way to dig and find your own answer @valaparthvi, thanks!

**Comment by valaparthvi** [comment]
@mshriver It was actually @Yadnyawalkya who pointed me towards that FAQ.😅
