### ISSUE TITLE
[Bug] If BZ is reported for version 5.9 and fixed in 5.10, it is not skipped

### ISSUE THREAD

**Issue by jan-zmeskal** [ManageIQ/integration_tests#7603]
Firstly, I noticed this behaviour because of this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1545240). `test_query_provider_attributes` [checks](https://github.com/ManageIQ/integration_tests/blob/ef2fc2dd243b35cf96007c81d3642e02711a4f11/cfme/tests/cloud_infra_common/test_rest_providers.py#L66) if this BZ blocks. At some point during processing of this BZ, [Bugzilla.resolve_blocker](https://github.com/ManageIQ/integration_tests/blob/ef2fc2dd243b35cf96007c81d3642e02711a4f11/cfme/utils/bz.py#L145) is called. The bug is added to the `filtered` set. But when execution gets to this [point](https://github.com/ManageIQ/integration_tests/blob/ef2fc2dd243b35cf96007c81d3642e02711a4f11/cfme/utils/bz.py#L196), `check_fixed_in` returns `False`. Therefore `bug` is not returned and instead `None` is returned. As a consequence, `False` is also returned during resolving property [blocks](https://github.com/ManageIQ/integration_tests/blob/ef2fc2dd243b35cf96007c81d3642e02711a4f11/cfme/utils/blockers.py#L187) of `BZ`.  As far as I understand, this is not expected behaviour. I believe this bug should resolve as blocking if it is in one of [Bugzilla.open_states](https://github.com/ManageIQ/integration_tests/blob/ef2fc2dd243b35cf96007c81d3642e02711a4f11/cfme/utils/bz.py#L107). It's nice that it's fixed in 5.10, but I still need to test 5.9 and skip this bug if necessary.

Additional info: I know that at time of reporting this issue, the BZ is acutally in ON_QA state. But that should still should make it blocking as I have ON_QA state included in env.yaml in `bugzilla[skip]`.

Also, [here](http://pastebin.test.redhat.com/627464) you can see how flow of `resolve_blockers` actually looks like when I was following it manually.

Sorry for the text wall, just wanted to spare you some debugging. :-)

**Comment by jan-zmeskal** [comment]
Creating #7604 as a workaround.

**Comment by mshriver** [comment]
I believe this has been resolved with @jaryn contribution here:

https://github.com/ManageIQ/integration_tests/pull/8208/files#diff-89e51f6d56a899c026153169db2576a5

We can re-open if we continue to see problems resolving blocker BZs
