### ISSUE TITLE
Resolve navigation failures due to wait_for_view

### ISSUE THREAD

**Issue by matejart** [ManageIQ/integration_tests#7960]
In [this commit](https://github.com/ManageIQ/integration_tests/commit/27c7ba9f8ee8797812c16774f3111357eda5472d#diff-8f65f83f3de1a967375f00c9f99ed6ccR514) the type of `nav_args["wait_for_view"]` changed from boolean to a numeric value. However, its usage [in condition at line 554 of cfme/utils/appliance/implementations/ui.py](https://github.com/ManageIQ/integration_tests/commit/27c7ba9f8ee8797812c16774f3111357eda5472d#diff-8f65f83f3de1a967375f00c9f99ed6ccR554) remains as a boolean check.

If someone set `wait_for_view` to `0`, they might mean "I want to check, but not wait for the result", while the logic would interpret that as `False` and skip the check altogether.

**Comment by mshriver** [comment]
I'm going to work on Issue2 above, `Message: Could not find an element Locator(by='xpath', locator=u'//div[@id="settings_co_categories"]/table')`

**Comment by digitronik** [comment]
I would like to work on Issue-3. Which related to `LineChart` tooltip. Let me first ask @nachandr.

**Comment by kedark3** [comment]
Issue I see when navigating host:

> raise ItemNotFound('Timed out navigating to details for: {}'.format(self))
> E           ItemNotFound: Timed out navigating to details for: Host(name=u'env-rhv42-03.cfme2.lab.eng.rdu2.redhat.com', provider=RHEVMProvider(endpoints={'default': <cfme.infrastructure.provider.rhevm.RHEVMEndpoint object at 0x7f76f8198c10>}, name='rhv42', key='rhv42', zone='default', start_ip='10.8.197.37', end_ip='10.8.197.37', provider_data=None), hostname=None, ip_address=None, custom_ident=None, host_platform=None, ipmi_address=None, mac_address=None, credentials={}, ipmi_credentials=None, interface_type='lan')
> 

It is happening on the function call `host_obj.get_tags()`

**Comment by mshriver** [comment]
There is a bug in wt.core, introduced with row/colspan support, that is impacting any of our views where a table widget is nested under a Tab - this applies to any tests that use the provisioning form, or tags.

https://github.com/RedHatQE/widgetastic.core/pull/121

**Comment by izapolsk** [comment]
I suppose this issue has already been fixed.

**Comment by digitronik** [comment]
@izapolsk agreed with you we are not facing this issue in results. I vote for `close`
