### ISSUE TITLE
SSA tests fail on flash message not being found

### ISSUE THREAD

**Issue by rhrazdil** [ManageIQ/integration_tests#8024]
SSA tests at one point edit Management engine of a provisioned VM. When the save button is clicked, the framework expects Flash message 'Management Engine Relationship saved'.

The flash message is correctly displayed, but framework fails to find it, so all SSA* tests fail on the following error:

![screenshot from 2018-10-22 15-59-05](https://user-images.githubusercontent.com/32546791/47296722-6f032580-d613-11e8-81dd-24ec4ba76030.png)

I tried to create the view od InfraVM Detail page while the flash message was still displayed in ipython and it worked, so the problem isn't in selecting the message: 

In [0]: from cfme.infrastructure.virtual_machines import InfraVmDetailsView
In [1]: view = appliance.browser.create_view(InfraVmDetailsView)
In [2]: f = view.flash.messages[0]
In [3]: f.type
Out[3]: u'success'
In [4]: f.text
Out[4]: u'Management Engine Relationship saved'
In [5]: view.flash.assert_success_message('Management Engine Relationship saved')

**Comment by jan-zmeskal** [comment]
Tracked in #8157
