### ISSUE TITLE
[Bug] test_run_host_analysis fails on waiting for ProviderAllHostsView

### ISSUE THREAD

**Issue by jan-zmeskal** [ManageIQ/integration_tests#8160]
Even though waiting for this view should have been fixed in #8105, [test_run_host_analysis](https://github.com/ManageIQ/integration_tests/blob/3e277887f1769b7f2cb558d0ef39b66b096f0501/cfme/tests/infrastructure/test_host_analysis.py#L66) still fails on waiting for this view. See [here](http://pastebin.test.redhat.com/670131).

**Comment by mshriver** [comment]
@jan-zmeskal can you provide a bit more information about the failure case you're seeing?

This is working in our environments against 5.9 and 5.10, against rhv and vmware providers (except 59z on rhv where its skipped due to BZ)

**Comment by jan-zmeskal** [comment]
@mshriver Your comment made me look more thoroughly into it and now I cannot reproduce it at all. It might be the case that I ran the test case from the old branch. Thank you, closing
