### ISSUE TITLE
py3: compatibility 

### ISSUE THREAD

**Issue by digitronik** [ManageIQ/integration_tests#8660]
As Py2.7 will retire at end of 2019. Better to move `integration test` fully and related `side-packages` on Py3.

**Comment by digitronik** [comment]
today I was facing some problem with `manageiq-rest` client. lib returning `map` object for some call which is not good for indexing. its should return `list` or `tuple`; `map` should not be return type. 

Added `issue`. If maintainer accept I would like to add fix else in `integration test` need to add `list compression`.

https://github.com/ManageIQ/manageiq-api-client-python/issues/47

**Comment by izapolsk** [comment]
@digitronik, is it still actual ?

**Comment by digitronik** [comment]
@izapolsk no;  rest problem solved; I was waiting for more issues related to comparability but as per my observation now we can close this.
