### ISSUE TITLE
Unable to read DB views 

### ISSUE THREAD

**Issue by nachandr** [ManageIQ/integration_tests#8943]
In 511, ' metrics' and 'metric_rollups' are views, but in 510, 'metrics' and 'metric_rollups' are tables.
Our DB client can only read tables and not views. Hence, our automated tests that try to access the metrics and metric_rollups views in 511 are failing.

511
=========================================================================
vmdb_production=# \d
 public | metric_rollups                                            | view     | root
 public | metric_rollups_01                                         | table    | root
 public | metric_rollups_02                                         | table    | root
 public | metric_rollups_03                                         | table    | root
 public | metrics                                                   | view     | root

=========================
510
=========================
 public | metric_rollups                                            | table    | root
 public | metric_rollups_01                                         | table    | root
 public | metric_rollups_02                                         | table    | root
 public | metrics                                                   | table    | root

**Comment by izapolsk** [comment]
This PR should sort out above issue https://github.com/ManageIQ/integration_tests/pull/8946
