### ISSUE TITLE
Support for grouped Report tables

### ISSUE THREAD

**Issue by mfalesni** [ManageIQ/integration_tests#968]
Reports have special tables, they have grouping rows which normal table fails reading (obviously if you use grouping, otherwise no problem). There are two obvious solutions:
- enable the table to skip "malformed" rows (the grouped value which is written in the row is usually repeated in each row of the record so it should not be such problem)
- create new class that would handle that.

**Comment by jkrocil** [comment]
Is this still valid?

**Comment by mfalesni** [comment]
I guess we still don't support grouped tables, so probably yes.

**Comment by mfalesni** [comment]
@nachandr will need this for chargeback automation.

**Comment by mshriver** [comment]
This support/issue is no longer needed.
